/**
 * Created by Asiel on 10/02/2018.
 */
 exports.{{model|capitalize}}={
    list:function(req,res){
        zun.repository.{{model}}.list({limit:parseInt(req.params.limit),offset:parseInt(req.params.offset)})
        .then(function(data){
            res.send(data)
        })
        .catch(function(error){
            res.status(500).send(error)
        })
    },
    getById:function(req,res){
        zun.repository.{{model}}.getById(req.params.id)
        .then(function(data){
            res.send(data)
        })
        .catch(function(error){
            res.status(500).send(error.message)
        })
    },
    create:function(req,res){
        zun.repository.{{model}}.create(req.body)
        .then(function(data){
            res.send(data);
        })
        .catch(function(error){
            res.status(500).send(error);
        })
    },
    update:function(req,res){
        zun.repository.{{model}}.update(req.params.id,req.body)
        .then(function(data){
            res.send(data);
        })
        .catch(function(error){
            res.status(500).send(error);
        })
    },
    delete:function(req,res){        
        zun.repository.{{model}}.delete(req.params.id)
        .then(function(data){
            res.send(data);
        })
        .catch(function(error){
            res.status(500).send(error)
        })
    }
}